using AutoMapper;
using ECX.HR.Application.DTOs.Addresss;
using ECX.HR.Application.DTOs.Allowances.cs;
using ECX.HR.Application.DTOs.Branchs;
using ECX.HR.Application.DTOs.Department;
using ECX.HR.Application.DTOs.DepositAutorizations;
using ECX.HR.Application.DTOs.Division;
using ECX.HR.Application.DTOs.Education;
using ECX.HR.Application.DTOs.EducationLevels;
using ECX.HR.Application.DTOs.EmergencyContacts;
using ECX.HR.Application.DTOs.EmployeePositions;
using ECX.HR.Application.DTOs.Employees;
using ECX.HR.Application.DTOs.OrganizationalProfiles;
using ECX.HR.Application.DTOs.Levels;
using ECX.HR.Application.DTOs.OrganizationalProfiles;
using ECX.HR.Application.DTOs.Positions;
using ECX.HR.Application.DTOs.Salaries;
using ECX.HR.Application.DTOs.Spouses;
using ECX.HR.Application.DTOs.Supervisors;
using ECX.HR.Application.DTOs.Trainings;
using ECX.HR.Application.DTOs.WorkExperiences;
using ECX.HR.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ECX.HR.Application.DTOs.EmployeeStatuss;
using ECX.HR.Application.CQRS.Addresss.Request.Queries;
using ECX.HR.Application.CQRS.Employee.Request.Queries;
using ECX.HR.Application.DTOs.Step;
using ECX.HR.Application.DTOs.AssignSupervisor;
using ECX.HR.Application.DTOs.LeaveBalance;
using ECX.HR.Application.DTOs.Leave;
using ECX.HR.Application.DTOs.PromotionVacancy;
using ECX.HR.Application.DTOs.Promotion;
using ECX.HR.Application.DTOs.PromotionRelation;
using ECX.HR.Application.DTOs.ActingAssigment;
using ECX.HR.Application.DTOs.Termination;
using ECX.HR.Application.DTOs.Holiday;
using ECX.HR.Application.CQRS.Attendance;
using ECX.HR.Application.DTOs.MedicalBalance;
using ECX.HR.Application.DTOs.MedicalFunds;
using ECX.HR.Application.DTOs.Payroll;
using ECX.HR.Application.DTOs.AllowanceType;
using ECX.HR.Application.DTOs.Deduction;
using ECX.HR.Application.DTOs.DeductionType;
using ECX.HR.Application.DTOs.Tax;
using ECX.HR.Application.DTOs.Bank;
using ECX.HR.Application.DTOs.OverTime;
using ECX.HR.Application.DTOs.TempPayroll;
using ECX.HR.Application.DTOs.PayrollContract;
using ECX.HR.Application.DTOs.Outsource;
using ECX.HR.Application.DTOs.Schedule;

namespace ECX.HR.Application.Profiles
{
    public class MappingProfiles : Profile
    {
        public MappingProfiles()
        {
            CreateMap<Adress, AddressDto>().ReverseMap();
            CreateMap<OutSources, OutsourceDto>().ReverseMap();

            CreateMap<Allowances, AllowanceDto>().ReverseMap();
            CreateMap<Branches, BranchDto>().ReverseMap();
            CreateMap<Department, DepartmentDto>().ReverseMap();
            CreateMap<DepositAutorizations, DepositAutorizationDto>().ReverseMap();
            CreateMap<Divisions, DivisionDto>().ReverseMap();
            CreateMap<Educations, EducationDto>().ReverseMap();
            CreateMap<EducationLevels, EducationLevelDto>().ReverseMap();
            CreateMap<EmergencyContacts, EmergencyContactDto>().ReverseMap();
            CreateMap<EmployeePositions, EmployeePositionDto>().ReverseMap();
            CreateMap<Employees, EmployeeDto>().ReverseMap();
            CreateMap<Employees, EmpCreateDto>().ReverseMap();
            CreateMap<EmployeeStatuss, EmployeeStatusDto>().ReverseMap();
            CreateMap<Levels, LevelDto>().ReverseMap();
            CreateMap<OrganizationalProfiles, OrganizationalProfileDto>().ReverseMap();
            CreateMap<Positions, PositionDto>().ReverseMap();
            CreateMap<SalaryTypes, SalaryTypeDto>().ReverseMap();
            CreateMap<Spouses, SpouseDto>().ReverseMap();
            CreateMap<Steps, StepDto>().ReverseMap();
            CreateMap<Supervisors, SupervisorDto>().ReverseMap();
            CreateMap<Trainings, TrainingDto>().ReverseMap();
            CreateMap<WorkExperiences, WorkExperienceDto>().ReverseMap();
            CreateMap<AssignSupervisorss, AssignSupervisorDto>().ReverseMap();
            CreateMap<AnnualLeaveBalances, AnnualLeaveBalanceDto>().ReverseMap();
            CreateMap<OtherLeaveBalances, OtherLeaveBalanceDto>().ReverseMap();
            CreateMap<LeaveTypes, LeaveTypeDto>().ReverseMap();
            CreateMap<LeaveRequests, LeaveRequestDto>().ReverseMap();
            CreateMap<PromotionVacancys, PromotionVacancyDto>().ReverseMap();
            CreateMap<Promotions, PromotionDto>().ReverseMap();
            CreateMap<PromotionRelations, PromotionRelationDto>().ReverseMap();
            CreateMap<ActingAssigments, ActingAssigmentDto>().ReverseMap();
            CreateMap<Terminations, TerminationDto>().ReverseMap();
            CreateMap<Holidays, HolidayDto>().ReverseMap();
            CreateMap<Attendances, AttendanceDto>().ReverseMap();
            CreateMap<MedicalBalances, MedicalBalanceDto>().ReverseMap();
            CreateMap<MedicalFunds, MedicalFundDto>().ReverseMap();
            CreateMap<TempPayrolls, TempPayRollDto>().ReverseMap();
             CreateMap<Payrolls, PayRollDto>().ReverseMap();
            CreateMap<AllowanceTypes, AllowanceTypeDto>().ReverseMap();
            CreateMap<Deductions, DeductionDto>().ReverseMap();
            CreateMap<DeductionTypes, DeductionTypeDto>().ReverseMap();
            CreateMap<Taxs, TaxDto>().ReverseMap();
            CreateMap<Banks, BankDto>().ReverseMap();
            CreateMap<OverTimes, OverTimeDto>().ReverseMap();
            CreateMap<PayrollContracts, PayrollContractDto>().ReverseMap();
            CreateMap<ContractEmployees, ContractRegistrationDto>().ReverseMap();

            CreateMap<NumOfRun, NumOfRunDto>().ReverseMap();
            CreateMap<USERINFO, UserInformationDto>().ReverseMap();
            CreateMap<NumRunDel, NumOfRunDto>().ReverseMap();
            CreateMap<CheckInOut, ChechInOutDto>().ReverseMap();
            CreateMap<UserOfNum, UserOfNumDto>().ReverseMap();
            CreateMap<SchClass, SchClassDto>().ReverseMap();
        }
    }
}
